version: '3.8'

services:
  # Infrastructure Services
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  postgres:
    image: timescale/timescaledb:latest-pg15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: football_analytics
      POSTGRES_USER: football_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/migrations:/docker-entrypoint-initdb.d

  influxdb:
    image: influxdb:2.7-alpine
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: football_metrics
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: dev_password
    volumes:
      - influxdb_data:/var/lib/influxdb2

  # Application Services
  api-gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.api-gateway
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: football_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: football_analytics
      INFLUXDB_HOST: influxdb
      INFLUXDB_PORT: 8086
      INFLUXDB_USERNAME: admin
      INFLUXDB_PASSWORD: dev_password
      INFLUXDB_DB: football_metrics
    depends_on:
      - redis
      - postgres
      - influxdb
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist

  websocket-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket-service
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WEBSOCKET_PORT: 8080
    depends_on:
      - redis
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
      VITE_WS_URL: ws://localhost:8080
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

volumes:
  redis_data:
  postgres_data:
  influxdb_data: