[build]
cmd = "npm install --prefix server"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "node api-service.js"

[env]
NODE_ENV = "production"
PORT = "3000"