[build]
cmd = "npm install"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "node server.js"

[env]
NODE_ENV = "production"
PORT = "3000"