[build]
cmd = "cd server && npm install"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "cd server && node api-service.js"

[env]
NODE_ENV = "production"
PORT = "3000"