#!/bin/bash

echo "🚀 Railway Deployment Commands"
echo "=============================="
echo ""
echo "Copy and paste these commands one by one in your terminal:"
echo ""
echo "1. Navigate to server directory:"
echo "cd /Users/isaac/Desktop/nfl:ncaa/server"
echo ""
echo "2. Login to Railway (will open browser):"
echo "railway login"
echo ""
echo "3. Initialize Railway project:"
echo "railway init --name sunday-edge-pro-api"
echo ""
echo "4. Set environment variables:"
echo "railway variables set ODDS_API_KEY=22e59e4eccd8562ad4b697aeeaccb0fb"
echo "railway variables set NODE_ENV=production" 
echo "railway variables set PORT=3001"
echo ""
echo "5. Deploy the app:"
echo "railway up"
echo ""
echo "6. Get your deployment URL:"
echo "railway domain"
echo ""
echo "After deployment, you'll get a URL like:"
echo "https://sunday-edge-pro-api-production-xxxx.up.railway.app"
echo ""
echo "📋 Copy that URL and come back - I'll update your frontend!"