apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion-service
  namespace: football-analytics
  labels:
    app: data-ingestion-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-ingestion-service
  template:
    metadata:
      labels:
        app: data-ingestion-service
    spec:
      containers:
      - name: data-ingestion-service
        image: football-analytics/data-ingestion-service:latest
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: football-analytics-config
              key: NODE_ENV
        - name: SPORTSDATA_API_KEY
          valueFrom:
            secretKeyRef:
              name: football-analytics-secrets
              key: SPORTSDATA_API_KEY
        - name: ESPN_API_KEY
          valueFrom:
            secretKeyRef:
              name: football-analytics-secrets
              key: ESPN_API_KEY
        - name: ODDS_API_KEY
          valueFrom:
            secretKeyRef:
              name: football-analytics-secrets
              key: ODDS_API_KEY
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: football-analytics-secrets
              key: WEATHER_API_KEY
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: football-analytics-config
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: football-analytics-secrets
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: data-ingestion-service
  namespace: football-analytics
spec:
  selector:
    app: data-ingestion-service
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-ingestion-service-hpa
  namespace: football-analytics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-ingestion-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80